import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BiUserPlus } from "react-icons/bi";
import Form from "../components/form";
import toast, { Toaster } from "react-hot-toast";

export default function Home() {
  return (
    <>
      <Head>
        <title>Employee Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="text-xl md:text-2xl text-center font-bold py-3">
          Employee Management
        </h1>
        <div className="container    border-b">
          <div className=" w-10/12 mx-auto">
            <div className="container mx-auto flex justify-between py-5">
              <div className="left flex gap-3">
                <button className="flex bg-indigo-500 text-white px-4 py-1 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800  ">
                  Add Employee
                  <span className="px-1">
                    <BiUserPlus size={23} />
                  </span>
                </button>
              </div>
            </div>
            {/* collapsable form */}
            <div className="container mx-auto py-3">
              <Form></Form>
            </div>

            {/* table */}
          </div>
        </div>
        <Toaster />
      </main>
    </>
  );
}
